### ISSUE TITLE
Edit structure picture

### ISSUE THREAD

**Issue by krboktv** [miguelmota/merkle-tree#2]
![image](https://user-images.githubusercontent.com/33546031/42370110-966330a6-8114-11e8-823d-d8c324c3defc.png)
Must be H8 = (H6 + H7)
This typo is contained in all the pictures😁

**Comment by DonleeIO** [comment]
@miguelmota If you still have the source files for the diagram pictures, could you address this or send them to me so that I can? Thanks.

**Comment by miguelmota** [comment]
@DonleeIO they're in the repo https://github.com/miguelmota/merkle-tree/tree/master/diagrams

You may import the XML file to draw.io. When saving as PNG make sure to save it as 200% the size for retina displays

**Comment by DonleeIO** [comment]
Thanks. I’ll do that as soon as possible.

**Comment by miguelmota** [comment]
closed by https://github.com/miguelmota/merkle-tree/commit/5eae50fe1eb93f4640428652ed83c2dd2e6f2b1a
